version: '2.4'

networks:
  internal:
    internal: true
  public:

services:
  netflow:
    container_name: netflow
    hostname: netflow
    image: ubnt/unms-netflow:1.2.6
    restart: unless-stopped

    depends_on:
    - postgres
    - rabbitmq
    - redis

    networks:
    - internal
    - public
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

    environment:
      UNMS_PG_HOST: postgres
      UNMS_RABBITMQ_HOST: rabbitmq
      UNMS_REDISDB_HOST: redis
      UNMS_NETFLOW_PORT: 2055
      UNMS_PG_PASSWORD: unms
      UNMS_PG_USER: unms
      UNMS_PG_DB: unms
      UNMS_PG_SCHEMA: unms

  nginx:
    container_name: nginx
    hostname: nginx
    #image: padhihomelab/nginx:1.19
    image: ubnt/unms-nginx:1.2.6
    restart: unless-stopped

    networks:
    - public
    - internal
    volumes:
    - ./data/unms/cert:/cert:rw
    - ./data/unms/firmwares:/www/firmwares:rw
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

    environment:
      SSL_CERT:
      SSL_CERT_KEY:
      SSL_CERT_CA:
      HTTP_PORT: 80
      HTTPS_PORT: 443
      SUSPEND_PORT: 81
      WS_PORT: 443
      UNMS_HTTP_PORT: 8081
      UNMS_WS_PORT: 8082
      UNMS_WS_SHELL_PORT: 8083
      UNMS_WS_API_PORT: 8084
      PUBLIC_HTTPS_PORT: 443
      SECURE_LINK_SECRET: Mi1kYw4y

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:9.6-alpine
    restart: unless-stopped

    networks:
    - internal
    volumes:
    - ./config/postgres:/docker-entrypoint-initdb.d:ro
    - ./data/postgres:/var/lib/postgresql/data/pgdata:rw
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

    command: postgres -c deadlock_timeout=5000 -c max_connections=512
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      UNMS_POSTGRES_DB: unms
      UNMS_POSTGRES_SCHEMA: unms
      UNMS_POSTGRES_USER: unms
      UNMS_POSTGRES_PASSWORD: unms
      UCRM_POSTGRES_DB: unms
      UCRM_POSTGRES_SCHEMA: ucrm
      UCRM_POSTGRES_USER: ucrm
      UCRM_POSTGRES_PASSWORD: ucrm
      PGDATA: /var/lib/postgresql/data/pgdata

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.8-alpine
    restart: unless-stopped

    networks:
    - internal
    volumes:
    - ./data/rabbitmq:/var/lib/rabbitmq:rw
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbit channel_max 4096'

  redis:
    container_name: redis
    hostname: redis
    image: redis:5.0-alpine
    restart: unless-stopped

    networks:
    - internal
    volumes:
    - ./data/redis:/data/db:rw
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

    command: redis-server --appendonly yes --dir /data/db/

  siridb:
    container_name: siridb
    #image: padhihomelab/siridb:2.0.37
    image: ubnt/unms-siridb:1.2.6
    restart: unless-stopped

    networks:
    - internal
    volumes:
    - ./data/siridb:/var/lib/siridb:rw
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

  ucrm:
    container_name: ucrm
    hostname: ucrm
    image: ubnt/unms-crm:3.2.7
    restart: unless-stopped

    depends_on:
    - postgres
    - rabbitmq
    - nginx

    networks:
    - public
    - internal
    volumes:
    - ./data/ucrm:/data:rw
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

    command: server_with_migrate
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: ucrm
      POSTGRES_SCHEMA: ucrm
      POSTGRES_USER: ucrm
      POSTGRES_DB: unms
      MAILER_ADDRESS: 127.0.0.1
      MAILER_ADDRESS_USERNAME: username
      MAILER_ADDRESS_PASSWORD: password
      SECRET: Mi1kYw4y
      SUSPEND_PORT: 81
      PUBLIC_HTTPS_PORT: 443
      UCRM_USER: unms
      UNMS_VERSION: 1.2.6
      UNMS_HOST: unms
      UNMS_PORT: 8081
      UNMS_TOKEN: Mi1kYw4y
      UNMS_BASE_URL: /v2.1
      UNMS_POSTGRES_SCHEMA: unms

  unms:
    container_name: unms
    hostname: unms
    image: ubnt/unms:1.2.6
    restart: unless-stopped

    depends_on:
    - redis
    - siridb
    - postgres
    - rabbitmq
    - nginx
    - ucrm

    networks:
    - public
    - internal
    volumes:
    - ./config/unms/health.sh:/health.sh:ro
    - ./data/unms:/home/app/unms/data:rw
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

    cap_add:
    - NET_ADMIN
    environment:
      UNMS_USER_ID: 1000
      UNMS_NGINX_HOST: nginx
      UNMS_PG_HOST: postgres
      UNMS_RABBITMQ_HOST: rabbitmq
      UNMS_REDISDB_HOST: redis
      UNMS_SIRIDB_HOST: siridb
      NODE_ENV: production
      HTTP_PORT: 8081
      WS_PORT: 8082
      WS_SHELL_PORT: 8083
      UNMS_WS_API_PORT: 8084
      UNMS_NETFLOW_PORT: 2055
      SSL_CERT:
      PUBLIC_HTTPS_PORT: 443
      PUBLIC_WS_PORT: 443
      NGINX_HTTPS_PORT: 443
      NGINX_WS_PORT: 443
      SUSPEND_PORT: 81
      BRANCH: master
      SECURE_LINK_SECRET: Mi1kYw4y
      UNMS_TOKEN: Mi1kYw4y
      CLUSTER_SIZE: auto
      UNMS_PG_PASSWORD: unms
      UNMS_PG_USER: unms
      UNMS_PG_DB: unms
      UNMS_PG_SCHEMA: unms
      USE_LOCAL_DISCOVERY: 'true'

    healthcheck:
      test: ["CMD", "bash", "/health.sh"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 5m
