version: "2.4"

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/29

services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    hostname: dnscrypt-proxy
    image: padhihomelab/dnscrypt-proxy:2.0.44
    restart: unless-stopped

    networks:
      pihole_net:
        ipv4_address: 10.0.0.2
    volumes:
    - ./dnscrypt-proxy.toml:/etc/dnscrypt-proxy.toml:ro

    environment:
      TZ: ${TZ:?}

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:v5.1.2
    restart: unless-stopped

    depends_on:
    - dnscrypt-proxy

    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    volumes:
    - ./etc_pihole:/etc/pihole:rw
    - ./etc_dnsmasq.d:/etc/dnsmasq.d:rw

    cap_add:
    - NET_BIND_SERVICE
    dns:
    - 127.0.0.1
    - 10.0.0.3
    environment:
      DNS1: '10.0.0.2#8053'
      DNS2: '10.0.0.2#8053'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      DNSMASQ_LISTENING: all
      IPv6: 'false'
      WEBPASSWORD: admin
      TZ: ${TZ:?}
