version: "2.4"

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/29

services:
  caddy:
    hostname: caddy
    image: caddy:2.2.0
    restart: unless-stopped
    user: ${USER_ID:?}

    depends_on:
    - pihole
  
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2
    volumes:
    - ./config/caddy/etc__caddy__Caddyfile:/etc/caddy/Caddyfile:ro
    - ./data/caddy/data:/data:rw
    - ./data/caddy/config:/config:rw

    environment:
      TZ: ${TZ:?}

  dnscrypt-proxy:
    hostname: dnscrypt-proxy
    image: padhihomelab/dnscrypt-proxy:2.0.44
    restart: unless-stopped

    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    volumes:
    - ./config/dnscrypt-proxy/etc__dnscrypt-proxy.toml:/etc/dnscrypt-proxy.toml:ro

    environment:
      TZ: ${TZ:?}

  pihole:
    hostname: pihole
    image: pihole/pihole:v5.1.2
    restart: unless-stopped

    depends_on:
    - dnscrypt-proxy

    networks:
      pihole_net:
        ipv4_address: 10.0.0.4
    volumes:
    - ./data/pihole/etc/pihole:/etc/pihole:rw
    - ./data/pihole/etc/dnsmasq.d:/etc/dnsmasq.d:rw

    cap_add:
    - NET_BIND_SERVICE
    dns:
    - 10.0.0.4
    - 127.0.0.1
    environment:
      DNS1: '10.0.0.3#8053'
      DNS2: '10.0.0.3#8053'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      DNSMASQ_LISTENING: all
      IPv6: 'false'
      WEBPASSWORD: admin
      TZ: ${TZ:?}
