version: '2.4'

networks:
  default:

services:
  caddy:
    hostname: caddy
    image: caddy:2.2.1
    restart: unless-stopped
    user: ${USER_ID:?}

    depends_on:
    - radarr
  
    volumes:
    - ./config/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    - ./data/caddy/data:/data:rw
    - ./data/caddy/config:/config:rw

    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "wget", "-qSO", "/dev/null", "http://localhost:2019/config"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

  radarr:
    image: padhihomelab/radarr:3.0.1.4259
    restart: unless-stopped

    volumes:
    - ./data/radarr/config:/config:rw
    - ./data/radarr/downloads:/downloads:rw
    - ./data/radarr/movies:/movies:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}
