version: '2.4'

networks:
  default:

services:
  caddy:
    hostname: caddy
    image: caddy:2.2.1
    restart: unless-stopped
    user: ${USER_ID:?}

    depends_on:
    - nzbget
    links:
    - openvpn:nzbget
  
    networks:
    - default
    volumes:
    - ./config/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    - ./data/caddy/data:/data:rw
    - ./data/caddy/config:/config:rw

    environment:
      TZ: ${TZ:?}

    healthcheck:
      test: ["CMD", "wget", "-qSO", "/dev/null", "http://localhost:2019/config"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s

  openvpn:
    hostname: openvpn
    image: padhihomelab/openvpn-client:2.4.9

    networks:
    - default
    volumes:
    - ./data/openvpn/config:/config:ro

    cap_add:
    - NET_ADMIN
    environment:
      CONFIG_FILE_NAME: 'client.conf'
      FORWARDED_PORTS: ''
      TZ: ${TZ:?}

  nzbget:
    image: padhihomelab/nzbget:21.0
    restart: unless-stopped

    depends_on:
    - openvpn

    network_mode: service:openvpn
    volumes:
    - ./data/nzbget/config:/config:rw
    - ./data/nzbget/data:/data:rw
    - ./downloads/complete:/downloads/complete:rw
    - ./downloads/incomplete:/downloads/incomplete:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
      TZ: ${TZ:?}
