version: "2.4"

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/29

services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    hostname: dnscrypt-proxy
    image: padhihomelab/dnscrypt-proxy:2.0.44
    restart: unless-stopped

    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:v5.0
    restart: unless-stopped

    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    volumes:
    - './etc_pihole:/etc/pihole'
    - './etc_dnsmasq.d:/etc/dnsmasq.d'

    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 10.0.0.3
    environment:
      DNS1: '10.0.0.2#8053'
      DNS2: '10.0.0.2#8053'
      IPv6: 'false'
      TZ: America/New_York
      DNSMASQ_LISTENING: all
      WEBPASSWORD: admin
