version: '2.4'

volumes:
  netdata_lib:
    driver_opts:
      type: tmpfs
      device: tmpfs
  netdata_cache:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  docker.sock-proxy:
    container_name: docker.sock-proxy
    hostname: docker.sock-proxy
    image: padhihomelab/docker.sock-proxy:2.2
    restart: unless-stopped

    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      CONTAINERS: '1'

  netdata:
    container_name: netdata
    hostname: netdata
    image: padhihomelab/netdata:1.24.0
    restart: unless-stopped

    depends_on:
    - docker.sock-proxy

    volumes:
    - netdata_lib:/var/lib/netdata:rw
    - netdata_cache:/var/cache/netdata:rw
    - ./charts.d.conf:/etc/netdata/charts.d.conf:ro
    - ./netdata.conf:/etc/netdata/netdata.conf:ro
    - /etc/group:/host/etc/group:ro
    - /etc/os-release:/host/etc/os-release:ro
    - /etc/passwd:/host/etc/passwd:ro
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro

    cap_add:
    - SYS_PTRACE
    environment:
      DO_NOT_TRACK: '1'
      DOCKER_HOST: docker.sock-proxy:1279
    security_opt:
    - apparmor:unconfined
