version: "2.4"

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/29

services:
  cloudflared:
    container_name: cloudflared
    hostname: cloudflared
    image: padhihomelab/cloudflared:20.07.1
    restart: unless-stopped

    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:v5.0
    restart: unless-stopped

    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    volumes:
    - './etc_pihole:/etc/pihole'
    - './etc_dnsmasq.d:/etc/dnsmasq.d'

    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - ''
    environment:
      DNS1: '10.0.0.2#5053'
      DNS2: '10.0.0.2#5053'
      IPv6: 'false'
      TZ: America/New_York
      DNSMASQ_LISTENING: all
      WEBPASSWORD: admin
