version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: padhihomelab/cloudflared:20.07.1
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole
    image: pihole/pihole:v5.0
    restart: unless-stopped
    hostname: pihole
    volumes:
      - "./etc_pihole:/etc/pihole"
      - "./etc_dnsmasq.d:/etc/dnsmasq.d"
    environment:
      - DNS1='10.0.0.2#5053'
      - DNS2=''
      - IPv6=false
      - TZ=America/New_York
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=admin
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - '127.0.0.1'
      - ''
    cap_add:
      - NET_ADMIN

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
