version: '2.4'

services:
  tang:
    hostname: tang
    image: padhihomelab/tang:git.8affe358_git.145c41a4
    restart: unless-stopped

    volumes:
    - ./data/tang/db:/db:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
