version: '2.4'

services:
  tang:
    hostname: tang
    image: padhihomelab/tang:git.95d48225_git.54bdd6dc
    restart: unless-stopped

    volumes:
    - ./data/tang/db:/db:rw

    environment:
      DOCKER_UID: ${USER_ID:?}
