name: Docker CI Release

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  test--pihole_cloudflared:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Docker: Compose prepare"
        run: |
          cp 'pihole+cloudflared/docker-compose.yml' .
      -
        name: "Docker: Compose start"
        run: |
          docker-compose up -d
          sleep 5s
      -
        name: "Docker: Compose test"
        run: |
          docker-compose exec -T pihole pihole status
