name: Docker CI Release

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  test--cloudflared_pihole:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Docker: Compose prepare"
        run: |
          cp 'cloudflared+pihole/docker-compose.yml' .
      -
        name: "Docker: Compose start"
        run: |
          docker-compose up -d
          sleep 5s
      -
        name: "Docker: Compose test"
        run: |
          docker-compose exec -T pihole pihole status

  test--docker-sock-proxy_netdata:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Docker: Compose prepare"
        run: |
          cp 'docker.sock-proxy+netdata/docker-compose.yml' 'docker.sock-proxy+netdata'/*.conf .
      -
        name: "Docker: Compose start"
        run: |
          docker-compose up -d
          sleep 5s
      -
        name: "Docker: Compose test"
        run: |
          REPLY="$(docker-compose exec -T netdata netdatacli ping)"
          [[ "$REPLY" == "pong" ]] || exit 1
