name: Docker CI Release

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      cloudflared_pihole: ${{ steps.filter.outputs.cloudflared_pihole }}
      docker-sock-proxy_netdata: ${{ steps.filter.outputs.docker-sock-proxy_netdata }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        filters: |
          cloudflared_pihole:
            - 'cloudflared+pihole/**/*'
          docker-sock-proxy_netdata:
            - 'docker.sock-proxy+netdata/**/*'

  test--cloudflared_pihole:
    needs: [changes]
    if: ${{ needs.changes.outputs.cloudflared_pihole == 'true' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Docker: Compose prepare"
        run: |
          cp 'cloudflared+pihole/docker-compose.yml' .
      -
        name: "Docker: Compose start"
        run: |
          docker-compose up -d
          sleep 5s
      -
        name: "Docker: Compose test"
        run: |
          docker-compose exec -T pihole pihole status

  test--docker-sock-proxy_netdata:
    needs: [changes]
    if: ${{ needs.changes.outputs.docker-sock-proxy_netdata == 'true' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Docker: Compose prepare"
        run: |
          cp 'docker.sock-proxy+netdata/docker-compose.yml' 'docker.sock-proxy+netdata'/*.conf .
      -
        name: "Docker: Compose start"
        run: |
          docker-compose up -d
          sleep 5s
      -
        name: "Docker: Compose test"
        run: |
          REPLY="$(docker-compose exec -T netdata netdatacli ping)"
          [[ "$REPLY" == "pong" ]] || exit 1
