name: Docker CI Release

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  test_pihole:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Service: Start"
        run: |
          ./service.sh up pihole
          sleep 30s
      -
        name: "Service: Test"
        run: |
          cd pihole
          docker-compose exec -T pihole pihole status
          docker-compose exec -T dnscrypt-proxy dig google.com

  test_netdata:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Service: Start"
        run: |
          ./service.sh up netdata
          sleep 5s
      -
        name: "Service: Test"
        run: |
          cd netdata
          REPLY="$(docker-compose exec -T netdata netdatacli ping)"
          [[ "$REPLY" == "pong" ]] || exit 1

  test_unifi:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Service: start"
        run: |
          ./service.sh up unifi
          sleep 30s
      -
        name: "Service: Test"
        run: |
          cd unifi
          docker-compose exec -T unifi bash /health.sh

  test_unms:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Service: Start"
        run: |
          ./service.sh up unms
          sleep 300s
      -
        name: "Service: Test"
        run: |
          cd unms
          docker-compose exec -T unms bash /health.sh
