name: "Docker Compose Test (nzbget)"

on:
  pull_request:
    branches: master
  push:
    branches: master
  schedule:
  - cron: "0 8 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Service: Setup"
        run: |
          mkdir -p nzbget/data/openvpn/config
          wget "https://www.vpngate.net/common/openvpn_download.aspx?sid=1608257730733&tcp=1&host=public-vpn-44.opengw.net&port=443&hid=15074629&/vpngate_public-vpn-44.opengw.net_tcp_443.ovpn" \
               -O nzbget/data/openvpn/config/client.conf
          echo -e "\nauth-user-pass login.txt" >> nzbget/data/openvpn/config/client.conf
          echo -e "vpn\nvpn" > nzbget/data/openvpn/config/login.txt
      -
        name: "Service: Start"
        run: |
          ./service.sh up --no-override nzbget
      -
        name: "Service: Wait"
        run: |
          sleep 45s
      -
        name: "Service: Test"
        run: |
          cd nzbget
          REPLY="$(docker inspect --format '{{json .State.Health.Status}}' $(docker-compose ps -q nzbget))"
          [[ "$REPLY" == '"healthy"' ]] || (docker-compose logs && exit 1)
          REPLY="$(docker inspect --format '{{json .State.Health.Status}}' $(docker-compose ps -q caddy))"
          [[ "$REPLY" == '"healthy"' ]] || (docker-compose logs && exit 1)
