name: Docker CI Release

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  test--dnscrypt-proxy_pihole:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Docker: Compose prepare"
        run: |
          cp -r 'dnscrypt-proxy+pihole'/* .
          rm -f docker-compose.override.yml
      -
        name: "Docker: Compose start"
        run: |
          docker-compose up -d
          sleep 30s
      -
        name: "Docker: Compose test"
        run: |
          docker-compose exec -T pihole pihole status
          docker-compose exec -T dnscrypt-proxy dig google.com

  test--docker-sock-proxy_netdata:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Docker: Compose prepare"
        run: |
          cp -r 'docker.sock-proxy+netdata'/* .
          rm -f docker-compose.override.yml
      -
        name: "Docker: Compose start"
        run: |
          docker-compose up -d
          sleep 5s
      -
        name: "Docker: Compose test"
        run: |
          REPLY="$(docker-compose exec -T netdata netdatacli ping)"
          [[ "$REPLY" == "pong" ]] || exit 1

  test--mongodb_unifi:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Git: Checkout"
        uses: actions/checkout@v2
      -
        name: "Docker: Compose prepare"
        run: |
          cp -r 'mongodb+unifi'/* .
          rm -f docker-compose.override.yml
      -
        name: "Docker: Compose start"
        run: |
          docker-compose up -d
          sleep 5s
      -
        name: "Docker: Compose test"
        run: |
          docker-compose exec -T unifi bash /health.sh
